# Description
# Ban IP yang gagal HTTP basic auth lebih dari 5x dalam 60 detik.
# Logpath mengarah ke nginx error.log, bukan access.log.

[nginx-http-auth]
enabled  = true
port     = http,https
filter   = nginx-http-auth.filter
logpath  = /var/log/nginx/error.log
maxretry = 5
findtime = 60
bantime  = 86400
action   = iptables-multiport
# Tambahkan management IP di sini, contoh: ignoreip = 127.0.0.1/8 ::1 10.0.0.0/24
ignoreip = 127.0.0.1/8 ::1
