[Definition]
# Match failed HTTP basic auth attempts dari nginx error log
failregex = ^ \[error\] \d+#\d+: \*\d+ user "(?:[^"]+|.*?)":? (?:password mismatch|was not found in ".*?"), client: <HOST>,
            ^ \[error\] \d+#\d+: \*\d+ no user/password was provided for basic authentication, client: <HOST>,

ignoreregex =
