# Description
# Repeated banned address will be ban for long time

[recidive]
enabled = true
filter = recidive.filter
logpath = /var/log/fail2ban.log
maxretry = 3
findtime = 2592000
bantime = -1
port = all
action = iptables-allports
ignoreip = 127.0.0.1/8 ::1
