[Definition]

datepattern = %%Y-%%m-%%dT%%H:%%M:%%S(?:\.%%f)?(?:Z|[+-]\d{2}:\d{2})

failregex = ^.*sshd\[\d+\]: Did not receive identification string from <HOST>\s*$
            ^.*sshd\[\d+\]: Connection (closed|reset) by (?:invalid user |authenticating user )?<HOST> port \d+\s*$
            ^.*sshd\[\d+\]: Disconnected from (?:invalid user |authenticating user )?<HOST> port \d+.*$

ignoreregex =
