# Description
# Basic security for wrong login attempts more than 3 times in 10 minutes.

[sshd]
enabled = true
port = ssh
filter   = ssh.filter
logpath  = /var/log/auth.log
maxretry = 3
findtime = 600
bantime  = 86400
action   = iptables-multiport
# Tambahkan management IP di sini, contoh: ignoreip = 127.0.0.1/8 ::1 10.0.0.0/24
ignoreip = 127.0.0.1/8 ::1
